// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthenticationResponse.proto

#ifndef PROTOBUF_INCLUDED_AuthenticationResponse_2eproto
#define PROTOBUF_INCLUDED_AuthenticationResponse_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_AuthenticationResponse_2eproto 

namespace protobuf_AuthenticationResponse_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_AuthenticationResponse_2eproto
class AuthenticationResponse;
class AuthenticationResponseDefaultTypeInternal;
extern AuthenticationResponseDefaultTypeInternal _AuthenticationResponse_default_instance_;
namespace google {
namespace protobuf {
template<> ::AuthenticationResponse* Arena::CreateMaybeMessage<::AuthenticationResponse>(Arena*);
}  // namespace protobuf
}  // namespace google

enum AuthenticationResponse_Status {
  AuthenticationResponse_Status_OK = 0,
  AuthenticationResponse_Status_FAIL = 1
};
bool AuthenticationResponse_Status_IsValid(int value);
const AuthenticationResponse_Status AuthenticationResponse_Status_Status_MIN = AuthenticationResponse_Status_OK;
const AuthenticationResponse_Status AuthenticationResponse_Status_Status_MAX = AuthenticationResponse_Status_FAIL;
const int AuthenticationResponse_Status_Status_ARRAYSIZE = AuthenticationResponse_Status_Status_MAX + 1;

const ::google::protobuf::EnumDescriptor* AuthenticationResponse_Status_descriptor();
inline const ::std::string& AuthenticationResponse_Status_Name(AuthenticationResponse_Status value) {
  return ::google::protobuf::internal::NameOfEnum(
    AuthenticationResponse_Status_descriptor(), value);
}
inline bool AuthenticationResponse_Status_Parse(
    const ::std::string& name, AuthenticationResponse_Status* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AuthenticationResponse_Status>(
    AuthenticationResponse_Status_descriptor(), name, value);
}
// ===================================================================

class AuthenticationResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AuthenticationResponse) */ {
 public:
  AuthenticationResponse();
  virtual ~AuthenticationResponse();

  AuthenticationResponse(const AuthenticationResponse& from);

  inline AuthenticationResponse& operator=(const AuthenticationResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthenticationResponse(AuthenticationResponse&& from) noexcept
    : AuthenticationResponse() {
    *this = ::std::move(from);
  }

  inline AuthenticationResponse& operator=(AuthenticationResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthenticationResponse* internal_default_instance() {
    return reinterpret_cast<const AuthenticationResponse*>(
               &_AuthenticationResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AuthenticationResponse* other);
  friend void swap(AuthenticationResponse& a, AuthenticationResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthenticationResponse* New() const final {
    return CreateMaybeMessage<AuthenticationResponse>(NULL);
  }

  AuthenticationResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AuthenticationResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AuthenticationResponse& from);
  void MergeFrom(const AuthenticationResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AuthenticationResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef AuthenticationResponse_Status Status;
  static const Status OK =
    AuthenticationResponse_Status_OK;
  static const Status FAIL =
    AuthenticationResponse_Status_FAIL;
  static inline bool Status_IsValid(int value) {
    return AuthenticationResponse_Status_IsValid(value);
  }
  static const Status Status_MIN =
    AuthenticationResponse_Status_Status_MIN;
  static const Status Status_MAX =
    AuthenticationResponse_Status_Status_MAX;
  static const int Status_ARRAYSIZE =
    AuthenticationResponse_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Status_descriptor() {
    return AuthenticationResponse_Status_descriptor();
  }
  static inline const ::std::string& Status_Name(Status value) {
    return AuthenticationResponse_Status_Name(value);
  }
  static inline bool Status_Parse(const ::std::string& name,
      Status* value) {
    return AuthenticationResponse_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .AuthenticationResponse.Status status = 1;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::AuthenticationResponse_Status status() const;
  void set_status(::AuthenticationResponse_Status value);

  // @@protoc_insertion_point(class_scope:AuthenticationResponse)
 private:
  void set_has_status();
  void clear_has_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  int status_;
  friend struct ::protobuf_AuthenticationResponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AuthenticationResponse

// required .AuthenticationResponse.Status status = 1;
inline bool AuthenticationResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthenticationResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthenticationResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthenticationResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::AuthenticationResponse_Status AuthenticationResponse::status() const {
  // @@protoc_insertion_point(field_get:AuthenticationResponse.status)
  return static_cast< ::AuthenticationResponse_Status >(status_);
}
inline void AuthenticationResponse::set_status(::AuthenticationResponse_Status value) {
  assert(::AuthenticationResponse_Status_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:AuthenticationResponse.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::AuthenticationResponse_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::AuthenticationResponse_Status>() {
  return ::AuthenticationResponse_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_AuthenticationResponse_2eproto
