// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DirectoryEntryList.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DirectoryEntryList_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DirectoryEntryList_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 4000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 4000000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "DirectoryEntryMessage.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DirectoryEntryList_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DirectoryEntryList_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DirectoryEntryList_2eproto;
class DirectoryEntryList;
class DirectoryEntryListDefaultTypeInternal;
extern DirectoryEntryListDefaultTypeInternal _DirectoryEntryList_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::DirectoryEntryList* Arena::CreateMaybeMessage<::DirectoryEntryList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class DirectoryEntryList PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DirectoryEntryList) */ {
 public:
  inline DirectoryEntryList() : DirectoryEntryList(nullptr) {}
  virtual ~DirectoryEntryList();

  DirectoryEntryList(const DirectoryEntryList& from);
  DirectoryEntryList(DirectoryEntryList&& from) noexcept
    : DirectoryEntryList() {
    *this = ::std::move(from);
  }

  inline DirectoryEntryList& operator=(const DirectoryEntryList& from) {
    CopyFrom(from);
    return *this;
  }
  inline DirectoryEntryList& operator=(DirectoryEntryList&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DirectoryEntryList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DirectoryEntryList* internal_default_instance() {
    return reinterpret_cast<const DirectoryEntryList*>(
               &_DirectoryEntryList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DirectoryEntryList& a, DirectoryEntryList& b) {
    a.Swap(&b);
  }
  inline void Swap(DirectoryEntryList* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DirectoryEntryList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DirectoryEntryList* New() const final {
    return CreateMaybeMessage<DirectoryEntryList>(nullptr);
  }

  DirectoryEntryList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DirectoryEntryList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DirectoryEntryList& from);
  void MergeFrom(const DirectoryEntryList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DirectoryEntryList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DirectoryEntryList";
  }
  protected:
  explicit DirectoryEntryList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_DirectoryEntryList_2eproto);
    return ::descriptor_table_DirectoryEntryList_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kListFieldNumber = 1,
  };
  // repeated .DirectoryEntryMessage list = 1;
  int list_size() const;
  private:
  int _internal_list_size() const;
  public:
  void clear_list();
  ::DirectoryEntryMessage* mutable_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage >*
      mutable_list();
  private:
  const ::DirectoryEntryMessage& _internal_list(int index) const;
  ::DirectoryEntryMessage* _internal_add_list();
  public:
  const ::DirectoryEntryMessage& list(int index) const;
  ::DirectoryEntryMessage* add_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage >&
      list() const;

  // @@protoc_insertion_point(class_scope:DirectoryEntryList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage > list_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DirectoryEntryList_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DirectoryEntryList

// repeated .DirectoryEntryMessage list = 1;
inline int DirectoryEntryList::_internal_list_size() const {
  return list_.size();
}
inline int DirectoryEntryList::list_size() const {
  return _internal_list_size();
}
inline ::DirectoryEntryMessage* DirectoryEntryList::mutable_list(int index) {
  // @@protoc_insertion_point(field_mutable:DirectoryEntryList.list)
  return list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage >*
DirectoryEntryList::mutable_list() {
  // @@protoc_insertion_point(field_mutable_list:DirectoryEntryList.list)
  return &list_;
}
inline const ::DirectoryEntryMessage& DirectoryEntryList::_internal_list(int index) const {
  return list_.Get(index);
}
inline const ::DirectoryEntryMessage& DirectoryEntryList::list(int index) const {
  // @@protoc_insertion_point(field_get:DirectoryEntryList.list)
  return _internal_list(index);
}
inline ::DirectoryEntryMessage* DirectoryEntryList::_internal_add_list() {
  return list_.Add();
}
inline ::DirectoryEntryMessage* DirectoryEntryList::add_list() {
  // @@protoc_insertion_point(field_add:DirectoryEntryList.list)
  return _internal_add_list();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage >&
DirectoryEntryList::list() const {
  // @@protoc_insertion_point(field_list:DirectoryEntryList.list)
  return list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DirectoryEntryList_2eproto
