// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobRequest.proto

#ifndef PROTOBUF_INCLUDED_JobRequest_2eproto
#define PROTOBUF_INCLUDED_JobRequest_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_JobRequest_2eproto 

namespace protobuf_JobRequest_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_JobRequest_2eproto
class JobRequest;
class JobRequestDefaultTypeInternal;
extern JobRequestDefaultTypeInternal _JobRequest_default_instance_;
namespace google {
namespace protobuf {
template<> ::JobRequest* Arena::CreateMaybeMessage<::JobRequest>(Arena*);
}  // namespace protobuf
}  // namespace google

enum JobRequest_PBAction {
  JobRequest_PBAction_ADD_FILE = 0,
  JobRequest_PBAction_ADD_DIRECTORY = 1,
  JobRequest_PBAction_UPDATE = 2,
  JobRequest_PBAction_DELETE = 3,
  JobRequest_PBAction_CANCELLED = 4
};
bool JobRequest_PBAction_IsValid(int value);
const JobRequest_PBAction JobRequest_PBAction_PBAction_MIN = JobRequest_PBAction_ADD_FILE;
const JobRequest_PBAction JobRequest_PBAction_PBAction_MAX = JobRequest_PBAction_CANCELLED;
const int JobRequest_PBAction_PBAction_ARRAYSIZE = JobRequest_PBAction_PBAction_MAX + 1;

const ::google::protobuf::EnumDescriptor* JobRequest_PBAction_descriptor();
inline const ::std::string& JobRequest_PBAction_Name(JobRequest_PBAction value) {
  return ::google::protobuf::internal::NameOfEnum(
    JobRequest_PBAction_descriptor(), value);
}
inline bool JobRequest_PBAction_Parse(
    const ::std::string& name, JobRequest_PBAction* value) {
  return ::google::protobuf::internal::ParseNamedEnum<JobRequest_PBAction>(
    JobRequest_PBAction_descriptor(), name, value);
}
// ===================================================================

class JobRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:JobRequest) */ {
 public:
  JobRequest();
  virtual ~JobRequest();

  JobRequest(const JobRequest& from);

  inline JobRequest& operator=(const JobRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  JobRequest(JobRequest&& from) noexcept
    : JobRequest() {
    *this = ::std::move(from);
  }

  inline JobRequest& operator=(JobRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JobRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JobRequest* internal_default_instance() {
    return reinterpret_cast<const JobRequest*>(
               &_JobRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(JobRequest* other);
  friend void swap(JobRequest& a, JobRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline JobRequest* New() const final {
    return CreateMaybeMessage<JobRequest>(NULL);
  }

  JobRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<JobRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const JobRequest& from);
  void MergeFrom(const JobRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JobRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef JobRequest_PBAction PBAction;
  static const PBAction ADD_FILE =
    JobRequest_PBAction_ADD_FILE;
  static const PBAction ADD_DIRECTORY =
    JobRequest_PBAction_ADD_DIRECTORY;
  static const PBAction UPDATE =
    JobRequest_PBAction_UPDATE;
  static const PBAction DELETE =
    JobRequest_PBAction_DELETE;
  static const PBAction CANCELLED =
    JobRequest_PBAction_CANCELLED;
  static inline bool PBAction_IsValid(int value) {
    return JobRequest_PBAction_IsValid(value);
  }
  static const PBAction PBAction_MIN =
    JobRequest_PBAction_PBAction_MIN;
  static const PBAction PBAction_MAX =
    JobRequest_PBAction_PBAction_MAX;
  static const int PBAction_ARRAYSIZE =
    JobRequest_PBAction_PBAction_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  PBAction_descriptor() {
    return JobRequest_PBAction_descriptor();
  }
  static inline const ::std::string& PBAction_Name(PBAction value) {
    return JobRequest_PBAction_Name(value);
  }
  static inline bool PBAction_Parse(const ::std::string& name,
      PBAction* value) {
    return JobRequest_PBAction_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string path = 2;
  bool has_path() const;
  void clear_path();
  static const int kPathFieldNumber = 2;
  const ::std::string& path() const;
  void set_path(const ::std::string& value);
  #if LANG_CXX11
  void set_path(::std::string&& value);
  #endif
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  ::std::string* mutable_path();
  ::std::string* release_path();
  void set_allocated_path(::std::string* path);

  // optional uint64 size = 3;
  bool has_size() const;
  void clear_size();
  static const int kSizeFieldNumber = 3;
  ::google::protobuf::uint64 size() const;
  void set_size(::google::protobuf::uint64 value);

  // required .JobRequest.PBAction pbaction = 1;
  bool has_pbaction() const;
  void clear_pbaction();
  static const int kPbactionFieldNumber = 1;
  ::JobRequest_PBAction pbaction() const;
  void set_pbaction(::JobRequest_PBAction value);

  // @@protoc_insertion_point(class_scope:JobRequest)
 private:
  void set_has_pbaction();
  void clear_has_pbaction();
  void set_has_path();
  void clear_has_path();
  void set_has_size();
  void clear_has_size();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr path_;
  ::google::protobuf::uint64 size_;
  int pbaction_;
  friend struct ::protobuf_JobRequest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JobRequest

// required .JobRequest.PBAction pbaction = 1;
inline bool JobRequest::has_pbaction() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void JobRequest::set_has_pbaction() {
  _has_bits_[0] |= 0x00000004u;
}
inline void JobRequest::clear_has_pbaction() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void JobRequest::clear_pbaction() {
  pbaction_ = 0;
  clear_has_pbaction();
}
inline ::JobRequest_PBAction JobRequest::pbaction() const {
  // @@protoc_insertion_point(field_get:JobRequest.pbaction)
  return static_cast< ::JobRequest_PBAction >(pbaction_);
}
inline void JobRequest::set_pbaction(::JobRequest_PBAction value) {
  assert(::JobRequest_PBAction_IsValid(value));
  set_has_pbaction();
  pbaction_ = value;
  // @@protoc_insertion_point(field_set:JobRequest.pbaction)
}

// required string path = 2;
inline bool JobRequest::has_path() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JobRequest::set_has_path() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JobRequest::clear_has_path() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JobRequest::clear_path() {
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_path();
}
inline const ::std::string& JobRequest::path() const {
  // @@protoc_insertion_point(field_get:JobRequest.path)
  return path_.GetNoArena();
}
inline void JobRequest::set_path(const ::std::string& value) {
  set_has_path();
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JobRequest.path)
}
#if LANG_CXX11
inline void JobRequest::set_path(::std::string&& value) {
  set_has_path();
  path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JobRequest.path)
}
#endif
inline void JobRequest::set_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_path();
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JobRequest.path)
}
inline void JobRequest::set_path(const char* value, size_t size) {
  set_has_path();
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JobRequest.path)
}
inline ::std::string* JobRequest::mutable_path() {
  set_has_path();
  // @@protoc_insertion_point(field_mutable:JobRequest.path)
  return path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JobRequest::release_path() {
  // @@protoc_insertion_point(field_release:JobRequest.path)
  if (!has_path()) {
    return NULL;
  }
  clear_has_path();
  return path_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JobRequest::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    set_has_path();
  } else {
    clear_has_path();
  }
  path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:JobRequest.path)
}

// optional uint64 size = 3;
inline bool JobRequest::has_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JobRequest::set_has_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void JobRequest::clear_has_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void JobRequest::clear_size() {
  size_ = GOOGLE_ULONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::uint64 JobRequest::size() const {
  // @@protoc_insertion_point(field_get:JobRequest.size)
  return size_;
}
inline void JobRequest::set_size(::google::protobuf::uint64 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:JobRequest.size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::JobRequest_PBAction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::JobRequest_PBAction>() {
  return ::JobRequest_PBAction_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_JobRequest_2eproto
