// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MachinePath.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MachinePath_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MachinePath_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 4000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 4000000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MachinePath_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MachinePath_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MachinePath_2eproto;
namespace BackupPB {
class MachinePath;
class MachinePathDefaultTypeInternal;
extern MachinePathDefaultTypeInternal _MachinePath_default_instance_;
}  // namespace BackupPB
PROTOBUF_NAMESPACE_OPEN
template<> ::BackupPB::MachinePath* Arena::CreateMaybeMessage<::BackupPB::MachinePath>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace BackupPB {

// ===================================================================

class MachinePath PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:BackupPB.MachinePath) */ {
 public:
  inline MachinePath() : MachinePath(nullptr) {}
  virtual ~MachinePath();

  MachinePath(const MachinePath& from);
  MachinePath(MachinePath&& from) noexcept
    : MachinePath() {
    *this = ::std::move(from);
  }

  inline MachinePath& operator=(const MachinePath& from) {
    CopyFrom(from);
    return *this;
  }
  inline MachinePath& operator=(MachinePath&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MachinePath& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MachinePath* internal_default_instance() {
    return reinterpret_cast<const MachinePath*>(
               &_MachinePath_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MachinePath& a, MachinePath& b) {
    a.Swap(&b);
  }
  inline void Swap(MachinePath* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MachinePath* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MachinePath* New() const final {
    return CreateMaybeMessage<MachinePath>(nullptr);
  }

  MachinePath* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MachinePath>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MachinePath& from);
  void MergeFrom(const MachinePath& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MachinePath* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "BackupPB.MachinePath";
  }
  protected:
  explicit MachinePath(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MachinePath_2eproto);
    return ::descriptor_table_MachinePath_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMachineIDFieldNumber = 1,
    kPathFieldNumber = 2,
  };
  // required string machineID = 1;
  bool has_machineid() const;
  private:
  bool _internal_has_machineid() const;
  public:
  void clear_machineid();
  const std::string& machineid() const;
  void set_machineid(const std::string& value);
  void set_machineid(std::string&& value);
  void set_machineid(const char* value);
  void set_machineid(const char* value, size_t size);
  std::string* mutable_machineid();
  std::string* release_machineid();
  void set_allocated_machineid(std::string* machineid);
  private:
  const std::string& _internal_machineid() const;
  void _internal_set_machineid(const std::string& value);
  std::string* _internal_mutable_machineid();
  public:

  // required string path = 2;
  bool has_path() const;
  private:
  bool _internal_has_path() const;
  public:
  void clear_path();
  const std::string& path() const;
  void set_path(const std::string& value);
  void set_path(std::string&& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  std::string* mutable_path();
  std::string* release_path();
  void set_allocated_path(std::string* path);
  private:
  const std::string& _internal_path() const;
  void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // @@protoc_insertion_point(class_scope:BackupPB.MachinePath)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr machineid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
  friend struct ::TableStruct_MachinePath_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MachinePath

// required string machineID = 1;
inline bool MachinePath::_internal_has_machineid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MachinePath::has_machineid() const {
  return _internal_has_machineid();
}
inline void MachinePath::clear_machineid() {
  machineid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MachinePath::machineid() const {
  // @@protoc_insertion_point(field_get:BackupPB.MachinePath.machineID)
  return _internal_machineid();
}
inline void MachinePath::set_machineid(const std::string& value) {
  _internal_set_machineid(value);
  // @@protoc_insertion_point(field_set:BackupPB.MachinePath.machineID)
}
inline std::string* MachinePath::mutable_machineid() {
  // @@protoc_insertion_point(field_mutable:BackupPB.MachinePath.machineID)
  return _internal_mutable_machineid();
}
inline const std::string& MachinePath::_internal_machineid() const {
  return machineid_.Get();
}
inline void MachinePath::_internal_set_machineid(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  machineid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MachinePath::set_machineid(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  machineid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:BackupPB.MachinePath.machineID)
}
inline void MachinePath::set_machineid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  machineid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:BackupPB.MachinePath.machineID)
}
inline void MachinePath::set_machineid(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  machineid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:BackupPB.MachinePath.machineID)
}
inline std::string* MachinePath::_internal_mutable_machineid() {
  _has_bits_[0] |= 0x00000001u;
  return machineid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MachinePath::release_machineid() {
  // @@protoc_insertion_point(field_release:BackupPB.MachinePath.machineID)
  if (!_internal_has_machineid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return machineid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MachinePath::set_allocated_machineid(std::string* machineid) {
  if (machineid != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  machineid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), machineid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BackupPB.MachinePath.machineID)
}

// required string path = 2;
inline bool MachinePath::_internal_has_path() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool MachinePath::has_path() const {
  return _internal_has_path();
}
inline void MachinePath::clear_path() {
  path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& MachinePath::path() const {
  // @@protoc_insertion_point(field_get:BackupPB.MachinePath.path)
  return _internal_path();
}
inline void MachinePath::set_path(const std::string& value) {
  _internal_set_path(value);
  // @@protoc_insertion_point(field_set:BackupPB.MachinePath.path)
}
inline std::string* MachinePath::mutable_path() {
  // @@protoc_insertion_point(field_mutable:BackupPB.MachinePath.path)
  return _internal_mutable_path();
}
inline const std::string& MachinePath::_internal_path() const {
  return path_.Get();
}
inline void MachinePath::_internal_set_path(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MachinePath::set_path(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  path_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:BackupPB.MachinePath.path)
}
inline void MachinePath::set_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:BackupPB.MachinePath.path)
}
inline void MachinePath::set_path(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:BackupPB.MachinePath.path)
}
inline std::string* MachinePath::_internal_mutable_path() {
  _has_bits_[0] |= 0x00000002u;
  return path_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MachinePath::release_path() {
  // @@protoc_insertion_point(field_release:BackupPB.MachinePath.path)
  if (!_internal_has_path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MachinePath::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BackupPB.MachinePath.path)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace BackupPB

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MachinePath_2eproto
