// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MetaInfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MetaInfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MetaInfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 4000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 4000000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "DirectoryEntryMessage.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MetaInfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MetaInfo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MetaInfo_2eproto;
class WorkspaceMetaInfo;
class WorkspaceMetaInfoDefaultTypeInternal;
extern WorkspaceMetaInfoDefaultTypeInternal _WorkspaceMetaInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::WorkspaceMetaInfo* Arena::CreateMaybeMessage<::WorkspaceMetaInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum WorkspaceMetaInfo_Status : int {
  WorkspaceMetaInfo_Status_OK = 0,
  WorkspaceMetaInfo_Status_NEW_DIRECTORY = 1,
  WorkspaceMetaInfo_Status_FAIL = 2
};
bool WorkspaceMetaInfo_Status_IsValid(int value);
constexpr WorkspaceMetaInfo_Status WorkspaceMetaInfo_Status_Status_MIN = WorkspaceMetaInfo_Status_OK;
constexpr WorkspaceMetaInfo_Status WorkspaceMetaInfo_Status_Status_MAX = WorkspaceMetaInfo_Status_FAIL;
constexpr int WorkspaceMetaInfo_Status_Status_ARRAYSIZE = WorkspaceMetaInfo_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WorkspaceMetaInfo_Status_descriptor();
template<typename T>
inline const std::string& WorkspaceMetaInfo_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, WorkspaceMetaInfo_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function WorkspaceMetaInfo_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    WorkspaceMetaInfo_Status_descriptor(), enum_t_value);
}
inline bool WorkspaceMetaInfo_Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, WorkspaceMetaInfo_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<WorkspaceMetaInfo_Status>(
    WorkspaceMetaInfo_Status_descriptor(), name, value);
}
// ===================================================================

class WorkspaceMetaInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:WorkspaceMetaInfo) */ {
 public:
  inline WorkspaceMetaInfo() : WorkspaceMetaInfo(nullptr) {}
  virtual ~WorkspaceMetaInfo();

  WorkspaceMetaInfo(const WorkspaceMetaInfo& from);
  WorkspaceMetaInfo(WorkspaceMetaInfo&& from) noexcept
    : WorkspaceMetaInfo() {
    *this = ::std::move(from);
  }

  inline WorkspaceMetaInfo& operator=(const WorkspaceMetaInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline WorkspaceMetaInfo& operator=(WorkspaceMetaInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WorkspaceMetaInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WorkspaceMetaInfo* internal_default_instance() {
    return reinterpret_cast<const WorkspaceMetaInfo*>(
               &_WorkspaceMetaInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(WorkspaceMetaInfo& a, WorkspaceMetaInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(WorkspaceMetaInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WorkspaceMetaInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WorkspaceMetaInfo* New() const final {
    return CreateMaybeMessage<WorkspaceMetaInfo>(nullptr);
  }

  WorkspaceMetaInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WorkspaceMetaInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WorkspaceMetaInfo& from);
  void MergeFrom(const WorkspaceMetaInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WorkspaceMetaInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "WorkspaceMetaInfo";
  }
  protected:
  explicit WorkspaceMetaInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MetaInfo_2eproto);
    return ::descriptor_table_MetaInfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef WorkspaceMetaInfo_Status Status;
  static constexpr Status OK =
    WorkspaceMetaInfo_Status_OK;
  static constexpr Status NEW_DIRECTORY =
    WorkspaceMetaInfo_Status_NEW_DIRECTORY;
  static constexpr Status FAIL =
    WorkspaceMetaInfo_Status_FAIL;
  static inline bool Status_IsValid(int value) {
    return WorkspaceMetaInfo_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    WorkspaceMetaInfo_Status_Status_MIN;
  static constexpr Status Status_MAX =
    WorkspaceMetaInfo_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    WorkspaceMetaInfo_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return WorkspaceMetaInfo_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return WorkspaceMetaInfo_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Status* value) {
    return WorkspaceMetaInfo_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kListFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // repeated .DirectoryEntryMessage list = 2;
  int list_size() const;
  private:
  int _internal_list_size() const;
  public:
  void clear_list();
  ::DirectoryEntryMessage* mutable_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage >*
      mutable_list();
  private:
  const ::DirectoryEntryMessage& _internal_list(int index) const;
  ::DirectoryEntryMessage* _internal_add_list();
  public:
  const ::DirectoryEntryMessage& list(int index) const;
  ::DirectoryEntryMessage* add_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage >&
      list() const;

  // required .WorkspaceMetaInfo.Status status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  ::WorkspaceMetaInfo_Status status() const;
  void set_status(::WorkspaceMetaInfo_Status value);
  private:
  ::WorkspaceMetaInfo_Status _internal_status() const;
  void _internal_set_status(::WorkspaceMetaInfo_Status value);
  public:

  // @@protoc_insertion_point(class_scope:WorkspaceMetaInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage > list_;
  int status_;
  friend struct ::TableStruct_MetaInfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WorkspaceMetaInfo

// required .WorkspaceMetaInfo.Status status = 1;
inline bool WorkspaceMetaInfo::_internal_has_status() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool WorkspaceMetaInfo::has_status() const {
  return _internal_has_status();
}
inline void WorkspaceMetaInfo::clear_status() {
  status_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::WorkspaceMetaInfo_Status WorkspaceMetaInfo::_internal_status() const {
  return static_cast< ::WorkspaceMetaInfo_Status >(status_);
}
inline ::WorkspaceMetaInfo_Status WorkspaceMetaInfo::status() const {
  // @@protoc_insertion_point(field_get:WorkspaceMetaInfo.status)
  return _internal_status();
}
inline void WorkspaceMetaInfo::_internal_set_status(::WorkspaceMetaInfo_Status value) {
  assert(::WorkspaceMetaInfo_Status_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  status_ = value;
}
inline void WorkspaceMetaInfo::set_status(::WorkspaceMetaInfo_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:WorkspaceMetaInfo.status)
}

// repeated .DirectoryEntryMessage list = 2;
inline int WorkspaceMetaInfo::_internal_list_size() const {
  return list_.size();
}
inline int WorkspaceMetaInfo::list_size() const {
  return _internal_list_size();
}
inline ::DirectoryEntryMessage* WorkspaceMetaInfo::mutable_list(int index) {
  // @@protoc_insertion_point(field_mutable:WorkspaceMetaInfo.list)
  return list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage >*
WorkspaceMetaInfo::mutable_list() {
  // @@protoc_insertion_point(field_mutable_list:WorkspaceMetaInfo.list)
  return &list_;
}
inline const ::DirectoryEntryMessage& WorkspaceMetaInfo::_internal_list(int index) const {
  return list_.Get(index);
}
inline const ::DirectoryEntryMessage& WorkspaceMetaInfo::list(int index) const {
  // @@protoc_insertion_point(field_get:WorkspaceMetaInfo.list)
  return _internal_list(index);
}
inline ::DirectoryEntryMessage* WorkspaceMetaInfo::_internal_add_list() {
  return list_.Add();
}
inline ::DirectoryEntryMessage* WorkspaceMetaInfo::add_list() {
  // @@protoc_insertion_point(field_add:WorkspaceMetaInfo.list)
  return _internal_add_list();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DirectoryEntryMessage >&
WorkspaceMetaInfo::list() const {
  // @@protoc_insertion_point(field_list:WorkspaceMetaInfo.list)
  return list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::WorkspaceMetaInfo_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::WorkspaceMetaInfo_Status>() {
  return ::WorkspaceMetaInfo_Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MetaInfo_2eproto
